apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: spring-petclinic
  namespace: multicluster-devsecops-development
spec:
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    server: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'