---
global:
  pattern: multicluster-devsecops

  options:
    useCSV: false
    syncPolicy: Automatic
    installPlanApproval: Automatic

  secure-registry:
    namespace: "openshift-storage"

    s3:
      # Values for S3 bucket access
      # Replace <region> with AWS region where S3 bucket was created
      # Replace <cluster-name> and <domain> with your OpenShift cluster values
      # bucketSource: "https://s3.<region>.amazonaws.com/com.redhat.myusername.mybucketname"
      bucketSource: "https://s3.us-west-2.amazonaws.com/com.redhat.ipbabble.wh-my-bucket"
      # Bucket base name used for xray images
      bucketBaseName: "wh-my-bucket"

  imageregistry:
    account: michael_souto
    hostname: quay.io
    type: quay

  git:
    hostname: github.com
    account: mikes429
    username: mikes429
    email: SOMEWHERE@EXAMPLE.COM
    dev_revision: demo

  quay:
    # Needs to be set consistently between hub and spoke clusters
    # TODO: Move back to the hub chart, store in a configmap, have an ACM policy distribute to spoke clusters, have spoke look up from configmap
    org:
      name: devel
      email: devel@myorg.com
    repo: example

main:
  clusterGroupName: hub
  opp: false
